spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev_psql
    username: admin
    password: 1998
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect